services:
  telegram-simple-server:
    build: .
    ports:
      - "${PORT:-7887}:${PORT:-7887}"
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: curl -f http://localhost:${PORT:-7887}/health
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s